version: "3.7"
services:
  demo-vue-project:
    image: node:12.4-alpine
    container_name: demo-vue-project
    working_dir: /app
    volumes:
      - ./:/app:cached
    environment:
      - VUE_APP_ENV=development
    expose:
      - 80
    ports:
      - "8080:8080"
    command: npm run serve
networks:
  default:
    external:
      name: demo.network
